language: android
sudo: required

android:
  components:
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository

script:
  - ./gradlew build

before_install:
  - cd Ledger
  - chmod +x gradlew
