language: android
sudo: required

android:
  components:
    - platform-tools
    - tools
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - cd Ledger
  - chmod +x gradlew
