language: android
sudo: required

android:
  components:
    - platform-tools
    - tools
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - sudo apt-get -qq update
  # ant-optional is needed for ant junit
  - sudo apt-get install ant-optional
